import { Strategy } from '../types';

export const mockStrategies: Strategy[] = [
  {
    id: 'covered-call',
    name: 'Covered Call',
    type: 'income',
    description: 'Generate income by selling call options against held assets',
    risk: 30,
    complexity: 'Basic',
    expectedYield: '8-15% APY',
    timeHorizon: '30-45 days',
    marketConditions: ['Sideways Market', 'Slightly Bullish', 'Low Volatility'],
    metrics: {
      risk: 30,
      complexity: 20,
      profitPotential: 40,
      timeCommitment: 25,
      capitalRequired: 70,
    },
    useCases: [
      'When you expect the market to move sideways or slightly up',
      'When you want to generate additional income from existing holdings',
      "When you're willing to limit upside potential for immediate income",
    ],
    actions: [
      'Hold or purchase 100 shares of the underlying asset',
      'Sell a call option against your shares',
      'Collect premium immediately',
      'Wait for option expiration or manage position as needed',
    ],
    example: {
      scenario: "Let's say you own 100 shares of ABC stock trading at $50 per share.",
      story: [
        'You believe ABC will stay around $50 or rise slightly over the next month',
        'You sell a call option with a $55 strike price, collecting $2 per share ($200 total) in premium',
        'If ABC stays below $55, you keep the full $200 premium as profit',
        'If ABC rises above $55, your shares might be called away, but you still profit from the premium and stock appreciation up to $55',
      ],
    },
  },
  {
    id: 'protective-put',
    name: 'Protective Put',
    type: 'protection',
    description: 'Hedge downside risk by purchasing put options for existing positions',
    risk: 25,
    complexity: 'Basic',
    expectedYield: '5-10% APY',
    timeHorizon: '60-90 days',
    marketConditions: ['Uncertain Market', 'High Volatility', 'Bearish Outlook'],
    metrics: {
      risk: 25,
      complexity: 20,
      profitPotential: 30,
      timeCommitment: 20,
      capitalRequired: 60,
    },
    useCases: [
      'When you want to protect against potential market downturns',
      'When you have significant unrealized gains',
      'When market uncertainty is high',
    ],
    actions: [
      'Hold or purchase the underlying asset',
      'Buy put options at desired strike price',
      'Monitor position and market conditions',
      'Exercise puts or sell if needed for protection',
    ],
    example: {
      scenario: 'You hold 100 shares of XYZ stock at $100 per share ($10,000 total investment).',
      story: [
        'Market conditions become uncertain and you want to protect your investment',
        'You purchase a put option with a $95 strike price for $2 per share ($200 total)',
        'If XYZ drops to $80, your put option allows you to sell at $95, limiting your loss',
        'If XYZ rises or stays flat, you only lose the $200 premium paid',
      ],
    },
  },
  {
    id: 'bull-call-spread',
    name: 'Bull Call Spread',
    type: 'growth',
    description: 'Profit from moderate price increases with limited risk',
    risk: 45,
    complexity: 'Intermediate',
    expectedYield: '15-25% APY',
    timeHorizon: '30-60 days',
    marketConditions: ['Bullish Trend', 'Moderate Volatility'],
    metrics: {
      risk: 45,
      complexity: 40,
      profitPotential: 60,
      timeCommitment: 30,
      capitalRequired: 50,
    },
    useCases: [
      'When you have a moderately bullish outlook',
      'When you want to limit potential losses',
      'When you want to reduce the cost of buying calls',
    ],
    actions: [
      'Buy a call option at a lower strike price',
      'Sell a call option at a higher strike price',
      'Monitor the position as the market moves',
      'Close or let expire at maturity',
    ],
    example: {
      scenario: 'Stock XYZ is trading at $100, and you expect it to rise to $110 in the next month.',
      story: [
        'You buy a $100 strike call for $3.00 ($300 total)',
        'You sell a $110 strike call for $1.00 ($100 total)',
        'Net cost of the spread is $2.00 ($200 total)',
        'Maximum profit of $800 if XYZ closes at or above $110 at expiration',
      ],
    },
  },
  {
    id: 'iron-condor',
    name: 'Iron Condor',
    type: 'income',
    description: 'Collect premium through a range-bound options strategy',
    risk: 40,
    complexity: 'Advanced',
    expectedYield: '12-20% APY',
    timeHorizon: '20-45 days',
    marketConditions: ['Range-Bound Market', 'Low Volatility', 'No Clear Trend'],
    metrics: {
      risk: 45,
      complexity: 80,
      profitPotential: 60,
      timeCommitment: 65,
      capitalRequired: 40,
    },
    useCases: [
      'When you expect the market to stay within a range',
      'When volatility is high and expected to decrease',
      'When you want to generate income with defined risk',
    ],
    actions: [
      'Sell an out-of-the-money put spread',
      'Sell an out-of-the-money call spread',
      'Monitor position for any breaches of short strikes',
      'Manage or close position before expiration',
    ],
    example: {
      scenario: 'Stock ABC is trading at $50 with high implied volatility.',
      story: [
        'You sell the 45/43 put spread and the 55/57 call spread',
        'Collect total premium of $0.80 ($80 per iron condor)',
        'Maximum profit achieved if ABC stays between $45 and $55',
        'Limited risk of $120 per iron condor if stock moves beyond wings',
      ],
    },
  },
  {
    id: 'pmcc',
    name: 'Poor Mans Covered Call',
    type: 'growth',
    description: 'Generate income with less capital using LEAPS options',
    risk: 55,
    complexity: 'Intermediate',
    expectedYield: '20-40% APY',
    timeHorizon: '6-18 months',
    marketConditions: ['Bullish Long-Term', 'Moderate Volatility'],
    metrics: {
      risk: 55,
      complexity: 40,
      profitPotential: 70,
      timeCommitment: 50,
      capitalRequired: 80,
    },
    useCases: [
      "When you're bullish on a stock but want to reduce capital requirements",
      'When you want to generate income while maintaining upside potential',
      'When you want to leverage your position with defined risk',
    ],
    actions: [
      'Buy a long-term deep ITM call option (LEAPS)',
      'Sell shorter-term OTM calls against your LEAPS',
      'Collect premium from short calls regularly',
      'Roll or adjust position as needed',
    ],
    example: {
      scenario: "Stock DEF is trading at $100, and you're bullish long-term.",
      story: [
        'You buy a 1-year $80 strike LEAPS call for $25 ($2,500)',
        'You sell monthly $105 strike calls for $1 ($100) each',
        'Over time, you can collect premium while the stock rises',
        'Potential to recover LEAPS cost through premium collection',
      ],
    },
  },
];
