name: Build

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm i

      - name: Build app
        run: pnpm run build
        env:
          VITE_ENV: 'dev'
          VITE_WHITELIST_MODE: true
          VITE_GRIX_API_KEY: ${{ secrets.VITE_GRIX_API_KEY }}
          VITE_PREMIA_KEY: ${{ secrets.VITE_PREMIA_KEY }}
